# **Homework**: Data talks club data engineering zoomcamp Data loading workshop

Hello folks, let's practice what we learned - Loading data with the best practices of data engineering.

Here are the exercises we will do

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.

In [ ]:
%%capture
!pip install dlt[duckdb]

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
sum=0
generator = square_root_generator(limit)

for sqrt_value in generator:
    print(sqrt_value)
    sum += sqrt_value
print(f'\nsum: {sum}\n')

# sum: 8.382332347441762

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979

sum: 8.382332347441762

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 13

generator = square_root_generator(limit)

for sqrt_value in generator:
    print(sqrt_value)
# 3.605551275463989

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0
3.1622776601683795
3.3166247903554
3.4641016151377544
3.605551275463989

# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**

1. Load the first generator and calculate the sum of ages of all people

In [132]:
# 1:
import dlt
import duckdb

age = 0
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in people_1():
  data_1 = person
  print(data_1)
  # age = data_1['age'].sum()
pipeline = dlt.pipeline(destination='duckdb', dataset_name='data_1')

info = pipeline.run(people_1(),
										table_name="people",
										write_disposition="replace")

print(info)



conn = duckdb.connect(f'{pipeline.pipeline_name}.duckdb')
conn.sql(f"SET search_path = '{pipeline.dataset_name}'")
print('Loaded tables')
display(conn.sql("show tables"))
people = conn.sql("select * from people").df()

print("\n\npeople table below:\n")
age = people['age'].sum()

display(f"sum of people_1 ages: {age}")

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
Pipeline dlt_colab_kernel_launcher load step completed in 0.20 seconds
1 load package(s) were loaded to destination duckdb and into dataset data_1
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1707686681.4575005 is LOADED and contains no failed jobs
Loaded tables

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people              │
│ people_1            │
└─────────────────────┘

people table below:

'sum of people_1 ages: 140'

2. Append the second generator to the same table as the first.

In [135]:
def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}


for person in people_2():
  data_2 = person
  print(data_2)

info = pipeline.run(people_2(),
										table_name="people",
										write_disposition="append")

print(info)

{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}
Pipeline dlt_colab_kernel_launcher load step completed in 0.20 seconds
1 load package(s) were loaded to destination duckdb and into dataset data_1
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1707686975.8956344 is LOADED and contains no failed jobs

In [136]:
conn = duckdb.connect(f'{pipeline.pipeline_name}.duckdb')
conn.sql(f"SET search_path = '{pipeline.dataset_name}'")
print('Loaded tables')
display(conn.sql("show tables"))

people = conn.sql("select * from people").df()

print("\n\npeople table below:\n")
age = people['age'].sum()

display(f"sum of people ages: {age}")
print('\n')
display(people)

Loaded tables

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people              │
│ people_1            │
│ people_2            │
└─────────────────────┘

people table below:

'sum of people ages: 353'

    id      name  age    city        _dlt_load_id         _dlt_id occupation
0    1  Person_1   26  City_A  1707686681.4575005  VbMZjk94/wZ6jg       None
1    2  Person_2   27  City_A  1707686681.4575005  D2xL4kBP7wzTJA       None
2    3  Person_3   28  City_A  1707686681.4575005  VuG/bP9OQoVwwg       None
3    4  Person_4   29  City_A  1707686681.4575005  mJ7S6P1795BfqQ       None
4    5  Person_5   30  City_A  1707686681.4575005  pE9f9Io7CPflrQ       None
5    3  Person_3   33  City_B  1707686975.8956344  3F/m+Ke/5PIj4Q      Job_3
6    4  Person_4   34  City_B  1707686975.8956344  nk513IHvgWjKuQ      Job_4
7    5  Person_5   35  City_B  1707686975.8956344  xudx1/6/Z5Ivqw      Job_5
8    6  Person_6   36  City_B  1707686975.8956344  BhOy3smc260OQg      Job_6
9    7  Person_7   37  City_B  1707686975.8956344  milbNq2X2Ovw6w      Job_7
10   8  Person_8   38  City_B  1707686975.8956344  nQincoJNCRA9RA      Job_8

In [ ]:
age = 0
age = people['age'].sum()
print(age)

353

In [ ]:
######################
# Testing and practice
######################
import json

def people():
    for i in range(1, 6):
        yield [{"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}]

    for x in range(3, 9):
        yield [{"ID": x, "Name": f"Person_{x}", "Age": 30 + x, "City": "City_B", "Occupation": f"Job_{x}"}]

people_list = list(people())
nested_json = {"People": people_list}
json_string = json.dumps(nested_json, indent=2)
print(json_string)

# pipeline = dlt.pipeline(destination='duckdb', dataset_name='people')

# info = pipeline.run(people(),
# 										table_name="people",
# 										write_disposition="merge",
#                     primary_key="record_hash")

# print(info)

In [ ]:
peops = conn.sql("""
select *
from people_2 p2
left join people_1 p1 on p2.id = p1.id
""").df()
print("\n\npeople 2 table below:\n")
display(peops)

# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

# Solution: First make sure that the following modules are installed:

In [95]:
#Install the dependencies
%%capture
!pip install dlt[duckdb]

In [142]:

import dlt
import duckdb


def people():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}


    # for x in range(3, 9):
    #     yield {"GUID":uuid.uuid4().hex, "ID": x, "Name": f"Person_{x}", "Age": 30 + x, "City": "City_B", "Occupation": f"Job_{x}"}

for data in people():
  print(data)

pipeline = dlt.pipeline(destination='duckdb', dataset_name='load_people')

# run the pipeline with default settings, and capture the outcome
info = pipeline.run(people(),
										table_name="people_M",
										write_disposition="replace",
                    primary_key="ID")
print(info)

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
Pipeline dlt_colab_kernel_launcher load step completed in 0.17 seconds
1 load package(s) were loaded to destination duckdb and into dataset load_people
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1707687254.8220794 is LOADED and contains no failed jobs

In [143]:
conn = duckdb.connect(f'{pipeline.pipeline_name}.duckdb')
conn.sql(f"SET search_path = '{pipeline.dataset_name}'")
print('Loaded tables')
display(conn.sql("show tables"))

people_M = conn.sql("select * from people_M").df()
display(people_M)

Loaded tables

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people              │
│ people_m            │
└─────────────────────┘

   id      name  age    city        _dlt_load_id         _dlt_id
0   1  Person_1   26  City_A  1707687254.8220794  EVy9HQSwpGtLUQ
1   2  Person_2   27  City_A  1707687254.8220794  KGHMlLqMjsTEHA
2   3  Person_3   28  City_A  1707687254.8220794  DTVQR9Kp1y58Qw
3   4  Person_4   29  City_A  1707687254.8220794  6SiI1ed6lTDNWg
4   5  Person_5   30  City_A  1707687254.8220794  mwyf0NRlLIXaEg

In [144]:

import dlt
import duckdb


def people():
    for x in range(3, 9):
        yield {"ID": x, "Name": f"Person_{x}", "Age": 30 + x, "City": "City_B", "Occupation": f"Job_{x}"}

for data in people():
  print(data)

pipeline = dlt.pipeline(destination='duckdb', dataset_name='load_people')

info = pipeline.run(people(),
					table_name='people_M',
					write_disposition="merge",
          primary_key = "ID")
print(info)

{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}
Pipeline dlt_colab_kernel_launcher load step completed in 0.37 seconds
1 load package(s) were loaded to destination duckdb and into dataset load_people
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1707687294.7090595 is LOADED and contains no failed jobs

In [145]:
conn = duckdb.connect(f'{pipeline.pipeline_name}.duckdb')
conn.sql(f"SET search_path = '{pipeline.dataset_name}'")
print('Loaded tables')
display(conn.sql("show tables"))

people_M = conn.sql("select * from people_M").df()
display(people_M)

Loaded tables

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people              │
│ people_m            │
└─────────────────────┘

   id      name  age    city        _dlt_load_id         _dlt_id occupation
0   1  Person_1   26  City_A  1707687254.8220794  EVy9HQSwpGtLUQ       None
1   2  Person_2   27  City_A  1707687254.8220794  KGHMlLqMjsTEHA       None
2   8  Person_8   38  City_B  1707687294.7090595  1Efn4sbkO3bLig      Job_8
3   7  Person_7   37  City_B  1707687294.7090595  59Nb6HVbvhUzOQ      Job_7
4   5  Person_5   35  City_B  1707687294.7090595  TkkaaRYh8xzc9A      Job_5
5   4  Person_4   34  City_B  1707687294.7090595  CV+7ac9+J/7v/Q      Job_4
6   3  Person_3   33  City_B  1707687294.7090595  rHJBxlQs/F29LQ      Job_3
7   6  Person_6   36  City_B  1707687294.7090595  C+cnvml4id79+w      Job_6

In [146]:
age = 0
age = people_M['age'].sum()
print(age)

266

In [ ]:
# # Print the error message
# print(traceback.format_exc())

# # Inspect the DuckDB client configuration
# print(DuckDBClient.get_config())

# Check the DuckDB version
print(duckdb.__version__)

0.9.2

Questions? difficulties? We are here to help.
- DTC data engineering course channel: https://datatalks-club.slack.com/archives/C01FABYF2RG
- dlt's DTC cohort channel: https://dlthub-community.slack.com/archives/C06GAEX2VNX